src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use phpDocumentor\Reflection\Types\Null_;
use phpDocumentor\Reflection\Types\Self_;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Il existe déja un compte avec cet email")
 * @UniqueEntity(fields={"pseudo"}, message="Ce pseudo existe déjà")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @var array<string>
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private ?string $pseudo;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private ?string $sex;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $level;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private ?string $postalcode;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private ?string $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private ?string $phone;

    /**
     * @ORM\Column(type="date")
     */
    private ?DateTime $birthdate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $lastname;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="friends")
     */
    private $friend;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="friend")
     */
    private $friends;

    /**
     * @ORM\OneToMany(targetEntity=TennisMatch::class, mappedBy="organizer", orphanRemoval=true)
     */
    private $tennisMatches;

    /**
     * @ORM\ManyToMany(targetEntity=TennisMatch::class, inversedBy="participent")
     */
    private $participationMatch;

    public function __construct()
    {
        $this->friend = new ArrayCollection();
        $this->friends = new ArrayCollection();
        $this->tennisMatches = new ArrayCollection();
        $this->participationMatch = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array<string> $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalcode(): ?string
    {
        return $this->postalcode;
    }

    public function setPostalcode(?string $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBirthdate(): ?DateTime
    {
        return $this->birthdate;
    }

    public function setBirthdate(DateTime $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getAge(): int
    {
        $date = new DateTime();
        $dateInterval = $this->birthdate->diff($date);

        return $dateInterval->y;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFriend(): Collection
    {
        return $this->friend;
    }

    public function addFriend(self $friend): self
    {
        if (!$this->friend->contains($friend)) {
            $this->friend[] = $friend;
        }

        return $this;
    }

    public function removeFriend(self $friend): self
    {
        $this->friend->removeElement($friend);

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFriends(): Collection
    {
        return $this->friends;
    }

    /**
     * @return Collection|TennisMatch[]
     */
    public function getTennisMatches(): Collection
    {
        return $this->tennisMatches;
    }

    public function addTennisMatch(TennisMatch $tennisMatch): self
    {
        if (!$this->tennisMatches->contains($tennisMatch)) {
            $this->tennisMatches[] = $tennisMatch;
            $tennisMatch->setOrganizer($this);
        }

        return $this;
    }

    public function removeTennisMatch(TennisMatch $tennisMatch): self
    {
        if ($this->tennisMatches->removeElement($tennisMatch)) {
            // set the owning side to null (unless already changed)
            if ($tennisMatch->getOrganizer() === $this) {
                $tennisMatch->setOrganizer(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return (string) $this->id;
    }

    /**
     * @return Collection|TennisMatch[]
     */
    public function getParticipationMatch(): Collection
    {
        return $this->participationMatch;
    }

    public function addParticipationMatch(TennisMatch $participationMatch): self
    {
        if (!$this->participationMatch->contains($participationMatch)) {
            $this->participationMatch[] = $participationMatch;
        }

        return $this;
    }

    public function removeParticipationMatch(TennisMatch $participationMatch): self
    {
        $this->participationMatch->removeElement($participationMatch);

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\CallbackTransformer;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', TextType::class, [
                'label' => 'Email',
            ])
/*          ->add('password') */ //We have to know how to re encrypte the password through this form
            ->add('pseudo', TextType::class, [
                'label' => 'Pseudo',
            ])
            ->add('sex', ChoiceType::class, [
                'label' => 'Sexe',
                'choices' => [
                    'Homme' => 'Homme',
                    'Femme' => 'Femme',
                    'Autre' => 'Autre',
                ]
            ])
            ->add('level', ChoiceType::class, [
                'label' => 'Niveau',
                'choices' => [
                    'Débutant' => 'Débutant',
                    'Intermediaire' => 'Intermediaire',
                    'Expert' => 'Expert',
                    'Professionnel' => 'Professionnel',
                ]
            ])
            ->add('address', TextType::class, [
                'required' => false,
                'label' => 'Adresse postale',
            ])
            ->add('postalcode', TextType::class, [
                'required' => false,
                'label' => 'Code postale',
            ])
            ->add('city', TextType::class, [
                'label' => 'Ville',
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'label' => 'Description',
            ])
            ->add('phone', TextType::class, [
                'required' => false,
                'label' => 'Telephone',
            ])
            ->add('birthdate', BirthdayType::class, [
                'label' => 'Date d\'anniversaire',
                'format' => 'dd-MM-yyyy',
                'placeholder' => [
                    'year' => 'Année', 'month' => 'Mois', 'day' => 'Jour',
                ],
                'years' => range(2003, 1930),
            ])
            ->add('firstname', TextType::class, [
                'label' => 'Prénom',
                'required' => false,
            ])
            ->add('lastname', TextType::class, [
                'label' => 'Nom',
                'required' => false,
            ])
            ->add('update', SubmitType::class, [
                'label' => 'Sauvegarder',
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_avatarForm.html.twig
<div class="editionForm">
    {{ form_start(formAvatar) }}
    <div class="containerEditionFormAvatar">
        <div class="editionItemFormAvatar">
            {{ form_row(formAvatar.avatar) }}
        </div>
        <div class="editionButtonsFormAvatar">
            <div class="updateButtonAvatar">{{ form_row(formAvatar.update) }}</div>
            <a class="backButtonEditAvatar" href="{{ path('user_profile', {'slug': user.slug}) }}">Retour</a>
            <a class="EditAccueilButtonAvatar" href="{{ path('user_index') }}">Accueil</a>
        </div>
    </div>
    {{ form_end(formAvatar) }}
</div>

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'slug': user.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer mon compte</button>
</form>

templates/user/_form.html.twig
<div class="editionForm">
    {{ form_start(editUserForm) }}
    <div class="containerEditionForm">
        <div class="editionItemForm editionItemEmail">
            {{ form_row(editUserForm.email) }}
        </div>
         <div class="editionItemForm">
            {{ form_row(editUserForm.firstname) }}
        </div>
         <div class="editionItemForm">
            {{ form_row(editUserForm.lastname) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.pseudo) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.sex) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.level) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.address) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.postalcode) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.city) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.phone) }}
        </div>
        <div class="editionBirtdateForm">
            {{ form_row(editUserForm.birthdate) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.description,{ 'attr': {'cols': '30', 'rows': '10' } }) }}
        </div>
        <div class="editionItemForm">
            {{ form_row(editUserForm.update) }}
        </div>
        {{ form_end(editUserForm) }}
            <a class="backButtonEditProfile" href="{{ path('user_profile', {'slug': user.slug}) }}">Retour</a>
            <a class="EditAccueilButton" href="{{ path('user_index') }}">Accueil</a>
            <div class="DeleteButtonEditProfile">{{ include('user/_delete_form.html.twig') }}</div>
            {# <a class="DeleteButtonEditProfile" href="{{ path('user_delete', {'id': user.id}) }}">Supprimer</a> #}
    </div>
</div>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Profile • Tencourt{% endblock %}

{% block body %}
    <div class="editionPage">
    <h1 class="editionTitleForm">Modifier mon profile</h1>
        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

        <div class="blankEditionPage"></div>
    </div>
{% endblock %}

templates/user/editAvatar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Avatar • TenCourt{% endblock %}

{% block body %}
<div class="containerEditAvatarBackground">
    <h1 class="editionTitleFormAvatar">Modifier mon avatar</h1>
    <div class="myProfileAvatarEdit">
    {% if user.avatar %}
		<img class="myProfilePicture  userPictureProfileShow" src="{{'/uploads/' ~ user.avatar }}"/>
        <a href="{{ path('user_delete_avatar', {'slug': user.slug}) }}">Supprimer</a>
    {% else %}
        <img class="myProfilePicture" src="{{ asset('build/images/profileDefault/anonymeAvatar.png') }}"/>
    {% endif %}
	</div>
    {{ include('user/_avatarForm.html.twig', {'button_label': 'Mettre à jour'}) }}

    {# <div class="blankMyEditAvatarPage"></div> #}
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs • Tencourt{% endblock %}

{% block body %}
<h1 class='searchTitleUsers'>Recherche rapide de joueurs</h1>
<div class="backgroundAllUsers">
    <div class='containerSearch'>
        {% for user in users %}
            <a class="containerPlayers" href="{{ path('user_show', {'slug': user.slug}) }}">
                <div class='players'>
                {% if user.avatar == null %}
                    <img class="playerPhoto" src="{{ asset('build/images/profileDefault/anonymeAvatar.png') }}"/>
                {% else %}
                    <img class="playerPhoto" src="{{ asset('/uploads/' ~ user.avatar) }}"/>
                {% endif %}
                    <div class="container_1_players">
                        <p class='playerItem playerPseudo'>{{user.pseudo}}</p>
                        <p class='playerItem playerSex'>{{user.sex}}</p>
                        <p class='playerItem playerAge'>{{user.age}} ans</p>
                        <p class='playerItem playerLevel'>{{user.level}}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
        <div class="blankShowUserPage"></div>
{#         <a href="{{ path('user_new') }}">
            Ajouter un joueur
        </a> #}
    </div>
</div>
{% endblock %}

templates/user/participations_matches.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participations • Tencourt{% endblock %}

{% block body %}
    <h1 class="myMatchesTitle">Mes participations</h1>
    <div class="containerMyMatchesBackground">
        <div class='myBlockListMatches'>
            <p class="CountParticipationMatchMessage">Nombre de participation(s): <span class="CountPariticipationMatchMessageAdd">{{ participationsMatches|length }}</span></p>
            {% for participation in participationsMatches|sort|reverse %}
                <a class="containerMatchlisting" href="{{ path('tennis_match_show', { 'id' : participation.id }) }}">
                    <div class="{{app.user.id != participation.organizer.id ? "matchListing" : "matchListingOwn"}}">
                        <p class="{{app.user.id != participation.organizer.id ? "matchListingTitleMatch" : "matchListingTitleMatchOwn"}}">{{ participation.name }}</p>
                        <p class="matchListingDateMatch">Le {{participation.eventDate|date("d/m/Y")}}  à {{participation.startHour|date("H")}}H{{participation.startHour|date("i")}}</p>
                        {% if app.user.id == participation.organizer.id %}
                            <p class="matchListingMessageOwner">Vous êtes l'organisateur de ce match</p>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
            <a class="backButtonParticipationMatchProfile" href="{{ path('user_profile', {'slug': user.slug}) }}">Retour</a>
        </div>
    <div class="blankMyProfileShowMatchPage"></div>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil • Tencourt{% endblock %}

{% block body %}
    <div class="containerMyProfile">
        {% for message in app.flashes('success') %}
                <div id="updateMessageSuccess" >
                    <p class="successModifiedMessage">{{ message }}</p>
                </div>
                <script language='javascript'>
                    temp=document.getElementById('updateMessageSuccess');
                    setTimeout('temp.style.display="none"',3000);
                </script>
        {% endfor %}
        <h1 class="myProfileTitle">Mon compte</h1>
        <div class="MyProfile">
            {% if user.avatar == NULL  %}
                <img class="myProfilePicture" src="{{ asset('build/images/profileDefault/anonymeAvatar.png') }}"/>
                <a class="ModifyAvatarButtonMyProfile" id= "editAvatar" href="{{ path('user_edit_avatar', {'id': user.id}) }}">Modifier</a>
            {% else %}
                <img class="userPictureProfileShow myProfilePicture" src="{{ asset('/uploads/' ~ user.avatar) }}"/>
                <a class="ModifyAvatarButtonMyProfile" id= "editAvatar" href="{{ path('user_edit_avatar', {'id': user.id}) }}">Modifier</a>
            {% endif %}
            <div class="myProfilePseudo">
                {{ user.pseudo}}
            </div>
            <div class="myProfileEmail">
                <p class="myProfileEmailTitle">Email</p>
                <p class="myProfileEmailValue">{{ user.email}}</p>
            </div>
            {% if user.firstname %}
            <div class="myProfileFirstname">
                <p class="myProfileFirstnameTitle">Prénom</p>
                <p class="myProfileFirstnameValue">{{user.firstname}}</p>
            </div>
            {% endif %}
            {% if user.lastname %}
            <div class="myProfileName">
                <p class="myProfileNameTitle">Nom</p>
                <p class="myProfileNameValue">{{user.lastname}}</p>
            </div>
            {% endif %}
            <div class="myProfileBirthday">
                <p class="myProfileBirthdateTitle">Date de naissance</p>
                <p class="myProfileBirthdayValue">{{ user.birthdate|date('d/m/Y') }}</p>
            </div>
            {% if user.phone %}
            <div class="myProfilePhone">
                <p class="myProfilePhoneTitle">Numero de téléphone</p>
                <p class="myProfilePhoneValue">{{ user.phone }}</p>
            </div>
            {% endif %}
            <div class="myProfileAdress">
            <p class="myProfileAddressTitle">Adresse postale</p>
                <p class="myProfileAddressValue">
                    {{ user.address}}
                    {{ user.postalcode}}
                    {{ user.city }}
                </p>
            </div>
        </div>
        <div class="myProfileContainerButtons">
            <div class="myProfileEdition">
                <a class="myProfileEditButton" href="{{ path('user_edit', {'slug': user.slug}) }}">Modifier mon profil</a>
            </div>
        </div>
         <div class="myProfileContainerButtons">
            <div class="myProfileEdition">
                <a class="myProfileEditButton" href="{{ path('user_update_password', {'slug': user.slug}) }}">Modifier mon mot de passe</a>
            </div>
        </div>
        <div class="myProfileMatchButton">
            <a href="{{ path('user_matches', {'slug': user.slug}) }}">Mes créations de matchs</a>
        </div>
        <div class="myProfileParticipationsButton">
            <a href="{{ path('user_participations_matches', {'slug': user.slug}) }}">Mes participations</a>
        </div>
        <div class="myProfileDeconnexion">
            <a class="myProfileDeconnexionButton" href = "{{ path('app_logout') }}">Déconnexion</a>
        </div>
        <div class="blankMyProfilePage"></div>
    </div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Profile de ' ~ user.pseudo ~ ' • Tencourt'}}{% endblock %}

{% block body %}
    <div class="backgroundShowUser">
        {% for message in app.flashes('success') %}
            <div id="updateMessageSuccess" >
                <p class="successModifiedMessage">{{ message }}</p>
            </div>
            <script language='javascript'>
                temp=document.getElementById('updateMessageSuccess');
                setTimeout('temp.style.display="none"',3000);
            </script>
        {% endfor %}
        <div class="containerUserProfileShow">
            {% if user.avatar == NULL  %}
                <img class="playerPhoto" src="{{ asset('build/images/profileDefault/anonymeAvatar.png') }}"/>
            {% else %}

                <img class="playerPhoto" src="{{ asset('/uploads/' ~ user.avatar) }}"/>

            {% endif %}
            <div class="userPseudoShow">
                <p class="userPseudoShowItem">{{ user.pseudo }}</p>
                <p class="userSexShowItem">{{ user.sex }}</p>
            </div>
            <div class="userDescriptionShow">
                <p>{{user.description}}</p>
            </div>
            <div class="userInformationShow">
                <p class="userInformationItem userAgeShow">{{user.age ~ ' ans'}}</p>
                <p class="userInformationItem userLocalisationShow">{{user.city}}</p>
                <p class="userInformationItem userLevelShow">{{user.level}}</p>
            </div>
        </div>
        <div class="userContactShow">
            {% if user.phone %}
                <div class="userContactPhone">Numéro de telephone:</div>
                <div class="userPhoneShow">{{user.phone}}</div>
            {% endif %} 
            <div class="userContactAddress">Adresse:</div>
            <div class="userAddressShow">{{user.address ~ ' ' ~ user.postalcode ~ ' ' ~ user.city}}</div>
            {% if user.slug != app.user.slug %}
            <div class="userEmailShow"><a href="{{ path('user_mail', {'slug': user.slug}) }}">Contacter</a></div>
            {% endif %}
            <div class="backButtonToUserList"><a href="{{ path('search_users')}}">Retour à la recherche</a></div>
        </div>
        <div class="blankEditionPage"></div>
    </div>
{% endblock %}

templates/user/show_match.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Matches • Tencourt{% endblock %}

{% block body %}
    <div class="containerMyMatchesBackground">
        {% for message in app.flashes('success') %}
                <div id="updateMessageSuccess" >
                    <p class="successModifiedMessage">{{ message }}</p>
                </div>
                <script language='javascript'>
                    temp=document.getElementById('updateMessageSuccess');
                    setTimeout('temp.style.display="none"',3000);
                </script>
        {% endfor %}
        <h1 class="myMatchesTitle">Mes matches</h1>
        <div class='myBlockListMatches'>
        <p class="CountCreationMatchMessage">Nombre de match(es) créé(s): <span class="CountCreationMatchMessageAdd">{{ matches|length }}</span></p>
            {% for match in matches|sort|reverse %}
                <a  class="containerMatchlisting" href="{{ path('tennis_match_show', { 'id' : match.id }) }}">
                    <div class="matchListingOwn">
                        <p class="matchListingTitleMatchOwn">{{ match.name }}</p>
                        <p class="matchListingDateMatch">Le {{match.eventDate|date("d/m/Y")}}  à {{match.startHour|date("H")}}H{{match.startHour|date("i")}}</p>
                    </div>
                </a>
            {% endfor %}
            <a class="backButtonShowMatchProfile" href="{{ path('user_profile', {'slug': user.slug}) }}">Retour</a>
        <div>
    </div>
    <div class="blankMyProfileShowMatchPage"></div>
{% endblock %}

templates/user/update_password.html.twig
{% extends "base.html.twig" %}

{% block body %}
<h1 class="updatePasswordTitle">Modifier le mot de passe</h1>
<div class="backgroundUpdatePasswordForm">
    {{ form_start(form) }}
    <div class="containerUpdatePasswordForm">
        <div class="updatePasswordItemForm">
            {{ form_row(form.oldPassword) }}
        </div>
         <div class="updatePasswordItemForm">
            {{ form_row(form.plainPassword) }}
        </div>
        <div class="updatePasswordItemForm">
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
        <a class="backButtonUpdatePassword" href="{{ path('user_profile', {'slug': user.slug}) }}">Retour</a>
    </div>
</div>
{% endblock %}